name: Release test
on:
  push:
    branches:
      - main

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    steps:
      - uses: actions/checkout@v2
      - name: installing dependencies
        run: yarn install
      - run: yarn prepare-next-release
      - name: publish tag
        run: git push --follow-tags